[package]
name = "audio-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
backend = { path = "backend", package = "audio-backend" }
log = "0.4"
rustyline = { version = "15", features = ["derive"], default-features = false }
simplelog = "0.12"
